//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class emergencia
    {
        public int emergencia_id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> usuario_atendeu_id { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string coordenada { get; set; }
        public Nullable<System.DateTime> datacriado { get; set; }
        public Nullable<int> deleted { get; set; }
        public Nullable<int> ativo { get; set; }
        public Nullable<int> id_kor { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
