//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    
    public partial class Listar_Conversas_Mensagens_Result
    {
        public int mensagem_id { get; set; }
        public Nullable<System.DateTime> datacriado { get; set; }
        public string texto { get; set; }
        public int usuario_id { get; set; }
        public string nome { get; set; }
        public Nullable<int> usuario_destino_id { get; set; }
        public string sentido { get; set; }
        public Nullable<int> count_mensagem { get; set; }
    }
}
