//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagem
    {
        public int imagem_id { get; set; }
        public string nome { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> id_fiscalizacao { get; set; }
        public Nullable<System.DateTime> datacriado { get; set; }
        public Nullable<int> ativo { get; set; }
        public string img_base64 { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual fiscalizacao fiscalizacao { get; set; }
    }
}
