//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class caixa_email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caixa_email()
        {
            this.anexo_caixa_email = new HashSet<anexo_caixa_email>();
        }
    
        public int caixa_email_id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public string destinatario { get; set; }
        public string remetente { get; set; }
        public string assunto { get; set; }
        public string texto { get; set; }
        public string tipo { get; set; }
        public Nullable<int> ativo { get; set; }
        public Nullable<int> enviado { get; set; }
        public Nullable<int> baixado { get; set; }
        public Nullable<System.DateTime> datacriado { get; set; }
        public Nullable<int> deleted { get; set; }
        public bool visualizado { get; set; }
        public Nullable<int> sincronizado { get; set; }
        public string cc { get; set; }
        public string message_id { get; set; }
    
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anexo_caixa_email> anexo_caixa_email { get; set; }
    }
}
