//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class anexo_mensagem
    {
        public int id_anexo_mensagem { get; set; }
        public Nullable<int> id_anexo { get; set; }
        public Nullable<int> mensagem_id { get; set; }
    
        public virtual anexo anexo { get; set; }
        public virtual mensagem mensagem { get; set; }
    }
}
