//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class anexo_caixa_email
    {
        public int id_anexo_caixa_email { get; set; }
        public Nullable<int> id_anexo { get; set; }
        public Nullable<int> caixa_email_id { get; set; }
    
        public virtual anexo anexo { get; set; }
        public virtual caixa_email caixa_email { get; set; }
        public virtual anexo_caixa_email anexo_caixa_email1 { get; set; }
        public virtual anexo_caixa_email anexo_caixa_email2 { get; set; }
    }
}
