//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class anexo_fiscalizacao
    {
        public int id_anexo_fiscalizacao { get; set; }
        public Nullable<int> id_anexo { get; set; }
        public Nullable<int> id_fiscalizacao { get; set; }
        public Nullable<int> id_tipo_fiscalizacao { get; set; }
    
        public virtual anexo anexo { get; set; }
        public virtual fiscalizacao fiscalizacao { get; set; }
        public virtual tipo_fiscalizacao tipo_fiscalizacao { get; set; }
    }
}
