//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_guia
    {
        public int id_item_guia { get; set; }
        public Nullable<int> id_tipo_materia_prima { get; set; }
        public string descricao_item { get; set; }
        public Nullable<int> id_guia { get; set; }
        public Nullable<int> qtd_item { get; set; }
        public string unidade_item { get; set; }
        public Nullable<decimal> valor_item { get; set; }
        public Nullable<int> ativo { get; set; }
        public Nullable<int> qtd_verificada { get; set; }
    
        public virtual guia guia { get; set; }
        public virtual tipo_materia_prima tipo_materia_prima { get; set; }
    }
}
