//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipofiscalizacao_operacao
    {
        public int id_fiscalizacao_operacao { get; set; }
        public Nullable<int> id_operacao { get; set; }
        public Nullable<int> id_tipo_fiscalizacao { get; set; }
    
        public virtual tipo_fiscalizacao tipo_fiscalizacao { get; set; }
        public virtual operacao operacao { get; set; }
    }
}
