//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class subtipo_fiscalizacao
    {
        public int id_subtipo_fiscalizacao { get; set; }
        public string desc_subtipo { get; set; }
        public int id_tipo_fiscalizacao { get; set; }
    
        public virtual tipo_fiscalizacao tipo_fiscalizacao { get; set; }
    }
}
