//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiKor
{
    using System;
    using System.Collections.Generic;
    
    public partial class conta_email
    {
        public int id_conta_email { get; set; }
        public int usuario_id { get; set; }
        public string smtp_host { get; set; }
        public Nullable<int> smtp_port { get; set; }
        public Nullable<int> smtp_auth { get; set; }
        public string smtp_username { get; set; }
        public string smtp_password { get; set; }
        public string pop3_host { get; set; }
        public Nullable<int> pop3_port { get; set; }
        public string pop3_username { get; set; }
        public string pop3_password { get; set; }
        public Nullable<int> pop3_delete { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
